### ISSUE TITLE
SPAN Integration will not initialize after HA 2023.5.x

### ISSUE THREAD

**Issue by nathan-curtis** [galak/span-hacs#12]
Error in Log:

```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/span_panel/__init__.py:87
Integration: Span Panel (documentation, issues)
First occurred: 1:45:34 PM (2 occurrences)
Last logged: 1:45:34 PM

Error setting up entry Span Panel nt-2235-xxxxxxl for span_panel
Error setting up entry Span Panel nt-2235-yyyyyy for span_panel
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/span_panel/__init__.py", line 87, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

Researching this:

"AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'"

Are we running afoul of this?
https://developers.home-assistant.io/blog/2022/07/08/config_entry_forwards/#:~:text=Integrations%20need%20to%20be%20refactored%20to%20replace%20calls,entities%20and%20platforms%20are%20still%20being%20set%20up.

**Comment by j4ys0n** [comment]
Any more info on this? i just updated everything and I'm seeing this same issue.
