### ISSUE TITLE
Getting 301 redirect for API

### ISSUE THREAD

**Issue by jeffkibuule** [galak/span-hacs#3]
I tried installing this integration but it looks like they changed the API location?

Traceback (most recent call last):
  File "/config/custom_components/span_panel/__init__.py", line 53, in async_update_data
    await span_panel.spaces.getData()
  File "/config/custom_components/span_panel/span_panel.py", line 231, in getData
    results.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/httpx/_models.py", line 736, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Redirect response '301 Moved Permanently' for url 'http://192.168.0.170/api/v1/spaces'
For more information check: https://httpstatuses.com/301

**Comment by galak** [comment]
What firmware version do you have?
Are you able to go to `http://192.168.0.170`?

**Comment by jeffkibuule** [comment]
My firmware is `spanos2/r202223/03`. I ended up fixing that issue in a fork. I want to send you a PR when I have something: https://github.com/jeffkibuule/span-hacs

So far I've added:
- Renaming spaces to circuits in codebase
- Seeing circuits in the energy tab

Still stumped on:
- Seeing total energy consumption of the panel in the energy tab.
- History of individual circuits shows total usage since install in detail view, not over the period of time specified.

<img width="1252" alt="Screen Shot 2022-08-10 at 10 15 52 AM" src="https://user-images.githubusercontent.com/734509/183924232-809486fa-afd9-4d65-9f8f-6301f1fe0e7b.png">
<img width="401" alt="Screen Shot 2022-08-10 at 10 16 13 AM" src="https://user-images.githubusercontent.com/734509/183924292-e9243299-9917-4c86-a7d0-80a5b8d087f8.png">

**Comment by galak** [comment]
> 

Interesting, I wonder if that is a newer or older firmware compared to `spanos2/r202216/04`.  How recent is your actual span panel? 

* On the history, I wasnt sure if I'm reporting the proper data to HA.  Need to chat w/some HA developers on that to better understand what we should be doing.
* For total consumption - not sure if in the API adding something, vs having just HA do the calculation.

**Comment by jeffkibuule** [comment]
My Span panel installation is from March 2022. I feel like the API on my device is newer, as accessing `api/v1/spaces` leaves the following message:

`{"detail":"'spaces' endpoint has been deprecated, switch to 'circuits'"}`

My model is `00200` if that matters.
